# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: FR_leg
  joint_model_group_pose: home_position
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - FLS_joint
    - FLL_joint
    - FLF_joint
    - FRS_joint
    - FRL_joint
    - FRF_joint
    - RLS_joint
    - RLL_joint
    - RLF_joint
    - RRS_joint
    - RRL_joint
    - RRF_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: FR_leg_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - FRS_joint
      - FRL_joint
      - FRF_joint
  - name: FL_leg_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - FLS_joint
      - FLL_joint
      - FLF_joint
  - name: RR_leg_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - RRS_joint
      - RRL_joint
      - RRF_joint
  - name: RL_leg_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - RLS_joint
      - RLL_joint
      - RLF_joint
  - name: Body_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - FLS_joint
      - FLL_joint
      - FLF_joint
      - FRS_joint
      - FRL_joint
      - FRF_joint
      - RLS_joint
      - RLL_joint
      - RLF_joint
      - RRS_joint
      - RRL_joint
      - RRF_joint